### PR TITLE
fix mingw CI by disabling glib option

### PR DESCRIPTION
**Pull request by uilianries**
Sync testing -> stable

### CODE REVIEW

**Comment by uilianries** [comment]
@ericLemanissier why do we need glib false for mingw? If it's a problem, we should also change the default option in the recipe, otherwise, the default package won't be available for mingw.

**Comment by ericLemanissier** [comment]
Currently it seems I cannot manage to build gettext for mingw, so it means glib cannot be compiled for mingw either.
Is there a way to set default options depending on the settings?

**Comment by SSE4** [comment]
let's hold on for now, I'll try to debug MinGW gettext issue tomorrow. I'll let you know if I find something useful.

**Comment by uilianries** [comment]
Any update?

**Comment by SSE4** [comment]
unfortunately, no luck fixing it, I'll try newer GLib version

**Comment by Croydon** [comment]
@uilianries @ericLemanissier @SSE4 

What is the current state of this? Can harfbuzz, glib and gettext be compiled with MinGW?

**Comment by ericLemanissier** [comment]
No progress on my side

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

**Pull request closed without merging**
