### PR TITLE
Add apple clang 9.1 job on travis file [build=outdated]

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Comment by SSE4** [comment]
missing ragel_installer/6.10@bincrafters/stable (not sure what is it)

**Comment by uilianries** [comment]
Hi @SSE4 

@sigmoidal created [ragel_installer](https://github.com/bincrafters/conan-ragel_installer) to solve ragel package. Harfbuzz needs ragel during build stage, including on Windows.

We could update ragell installer OR use the system package manager to install it.

Regarding that harfbuzz is an official package on Conan center and ragell_installer is not. Thus, if we are considering update ragell_installer, it should be fine enough to be promoted on Conan center.

**Comment by SSE4** [comment]
@uilianries sorry for the stupid question, but how one could use harfbuzz from conan-centre, if its dependency ragel_installer is not on conan-centre?

**Comment by solvingj** [comment]
We could handle this a few ways.  I think we should revisit `ragel_installer` for windows and get it submitted to conan center.  Then, when it's accepted, change harfbuzz recipe to use it.  

Of note, I think it's just a `package_id()` issue.

**Review by SSE4 — APPROVED** [review]
LGTM

**Pull request merged**
