### PR TITLE
testing->stable

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by uilianries** [comment]
Well, we dont have glib/2.58.3@bincrafters/stable built for clang9 and apple-clang11

**Comment by ericLemanissier** [comment]
we have glib/2.58.3@bincrafters/stable built for clang9 since today, but unfortunately nothing for apple clang 11, because of a bug in meson, which will be solved in meson 0.53.0

**Comment by uilianries** [comment]
> we have glib/2.58.3@bincrafters/stable built for clang9 since today, but unfortunately nothing for apple clang 11, because of a bug in meson, which will be solved in meson 0.53.0

Thanks for sharing it!

**Comment by Croydon** [comment]
Feel free to merge despite the XCode 11 missing prebuilds error. It is not breaking something already existing so it is fine

**Pull request merged**
